apiVersion: v1
kind: Service
metadata:
  name: vote
spec:
  type: NodePort        # exposes to your machine
  selector:
    app: vote
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000   # access at localhost:31000